/**
 * ﻿Copyright (C) 2012
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */

package org.n52.shared.session;

/**
 * Builds session information for a user and a given session id.<br>
 * <br>
 * It it recommended to create a random session id which can not be guessed easily, e.g. via
 * 
 * <pre>
 * {@code 
 * SessionInfo sessionInfo = SessionInfoBuilder.aLoginSession(domain, sessionId)
 *                                  .forUser(username)
 *                                  .withUserId(userId)
 *                                  .withRole(role)
 *                                  .build();
 * </pre>
 */
public class SessionInfoBuilder {
    private SessionInfo sessionInfo;

    public SessionInfoBuilder(String sessionId) {
        this.sessionInfo = new SessionInfo(sessionId);
    }

    /**
     * @param sessionId
     *        the session id generated by the server.
     * @return a {@link SessionInfoBuilder} instance to build a {@link SessionInfo}.
     */
    public static SessionInfoBuilder aSessionInfo(String sessionId) {
        return new SessionInfoBuilder(sessionId);
    }

    public SessionInfoBuilder forUser(String username) {
        sessionInfo.setUsername(username);
        return this;
    }

    public SessionInfoBuilder withRole(String role) {
        sessionInfo.setRole(role);
        return this;
    }

    public SessionInfoBuilder withUserId(String userId) {
        sessionInfo.setUserId(userId);
        return this;
    }
    
    /**
     * Builds the session info object.
     * 
     * @return a {@link SessionInfo}
     */
    public SessionInfo build() {
        return sessionInfo;
    }
}